// components/entity-chart/index.tsx
'use client'

import type { ChartData } from 'chart.js'
import React, { useMemo } from 'react'

import type { NucEntityChartInterface } from 'nucleify'
import { AdChart, type ChartType, useChart } from 'nucleify'

export const NucEntityChart: React.FC<NucEntityChartInterface> = (props) => {
  const { setChartData, setChartOptions } = useChart()

  const chartOptions = useMemo(() => {
    if (!props.type) return {}

    return setChartOptions(props.type as ChartType, props.direction)
  }, [props.type, props.direction, setChartOptions])

  const chartData: ChartData | undefined = useMemo(() => {
    const data = setChartData(
      props.chartMethodType,
      props.data?.activity,
      props.data?.article,
      props.data?.contact,
      props.data?.file,
      props.data?.money,
      props.data?.question,
      props.data?.technology,
      props.data?.user,
      props.example
    )
    if (!data) return undefined
    return {
      ...data,
      labels: data.labels ? [...data.labels] : data.labels,
    }
  }, [
    props.chartMethodType,
    props.data?.activity,
    props.data?.article,
    props.data?.contact,
    props.data?.file,
    props.data?.money,
    props.data?.question,
    props.data?.technology,
    props.data?.user,
    props.example,
    setChartData,
  ])

  return (
    <AdChart
      data={chartData}
      options={chartOptions}
      type={props.type}
      chartMethodType={props.chartMethodType}
      direction={props.direction}
      className={props.chartClass}
      example={props.example}
    />
  )
}

// atomic/template/entity-chart/index.vue
<template>
	<ad-chart 
		:data="chartData" 
		:options="chartOptions" 
		:type="props.type" 
		:chart-method-type="props.chartMethodType"
		:direction="props.direction" 
		:class="props.chartClass" 
		:example="props.example"
	/>
</template>

<script setup lang="ts">
import type { NucEntityChartInterface } from './types'
import { useChart } from './utils'

const props = defineProps<NucEntityChartInterface>()
const { chartData, setChartData, setChartOptions } = useChart()

const chartOptions = ref(setChartOptions(props.type, props.direction))

onMounted(() => {
  const initialData = setChartData(
    props.chartMethodType,
    props.data?.activity,
    props.data?.article,
    props.data?.contact,
    props.data?.file,
    props.data?.money,
    props.data?.question,
    props.data?.technology,
    props.data?.user,
    props.example
  )
  if (initialData) chartData.value = initialData

  if (props.example) {
    const randomizedData = setChartData(
      props.chartMethodType,
      props.data?.activity,
      props.data?.article,
      props.data?.contact,
      props.data?.file,
      props.data?.money,
      props.data?.question,
      props.data?.technology,
      props.data?.user,
      true
    )
    if (randomizedData) chartData.value = randomizedData
  }
})

watch(
  () => ({
    method: props.chartMethodType,
    example: props.example,
    data: props.data,
  }),
  () => {
    const watchedData = setChartData(
      props.chartMethodType,
      props.data?.activity,
      props.data?.article,
      props.data?.contact,
      props.data?.file,
      props.data?.money,
      props.data?.question,
      props.data?.technology,
      props.data?.user,
      props.example
    )
    if (watchedData) chartData.value = watchedData
  },
  { immediate: true, deep: true }
)
</script>
