// atomic/templates/chart-settings-card/index.vue
<template>
  <ad-card class="settings-card">
    <template #header>
      <div class="settings-card-header-container">
        <ad-heading :tag="4" :text="props.heading || 'Settings'" />

        <ad-button
          icon="prime:refresh"
          nui-type="main"
          class="refresh-button"
          rounded
          text
          @click="displayChartsStore.setAllTo(true)"
        />
      </div>
    </template>
    <template #content>
      <div
        v-for="group in displayChartGroups"
        :key="group.name"
        class="settings-card-group"
      >
        <h4 class="settings-card-group-title">{{ group.name }}</h4>
        <ul class="settings-card-item-list">
          <li
            v-for="item in group.items"
            :key="item"
            class="settings-card-item"
          >
            <ad-label :label="item" :for="item" />

            <ad-select-button
              nui-type="main"
              :model-value="displayCharts[item].value ? 'On' : 'Off'"
              :options="options"
              @click="displayChartsStore.toggle(item)"
            />
          </li>
        </ul>
      </div>
    </template>
  </ad-card>
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { ref } from 'vue'

import { displayChartGroups, useDisplayChartsStore } from 'nucleify'

const props = defineProps<{
  heading: string
}>()

const displayChartsStore = useDisplayChartsStore()
const displayCharts = storeToRefs(displayChartsStore)
const options = ref(['On', 'Off'])
</script>

// atomic/templates/chart-settings-card/index.tsx
'use client'

import type { JSX } from 'react'
import { useMemo } from 'react'

import type {
  NucChartSettingsCardInterface,
  NucDisplayChartsStateKeyType,
} from 'nucleify'
import {
  AdLabel,
  AdSelectButton,
  getDisplayChartGroups,
  NucSettingsCard,
  useDisplayChartsStore,
} from 'nucleify'

const options = ['On', 'Off']

export function NucChartSettingsCard({
  heading,
}: NucChartSettingsCardInterface): JSX.Element {
  const displayChartsStore = useDisplayChartsStore()
  const displayChartGroups = useMemo(() => getDisplayChartGroups(), [])

  return (
    <NucSettingsCard
      heading={heading || 'Settings'}
      showButton
      onButtonClick={() => displayChartsStore.setAllTo(true)}
    >
      {displayChartGroups.map((group) => (
        <div key={group.name} className="settings-card-group">
          <h4 className="settings-card-group-title">{group.name}</h4>
          <ul className="settings-card-item-list">
            {(group.items ?? []).map((item) => (
              <li key={item} className="settings-card-item">
                <AdLabel label={item} forInput={item} />
                <AdSelectButton
                  adType="main"
                  value={
                    displayChartsStore[item as NucDisplayChartsStateKeyType]
                      ? 'On'
                      : 'Off'
                  }
                  options={options}
                  onChange={() =>
                    displayChartsStore.toggle(
                      item as NucDisplayChartsStateKeyType
                    )
                  }
                />
              </li>
            ))}
          </ul>
        </div>
      ))}
    </NucSettingsCard>
  )
}
